apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
  namespace: inventory-service
type: Opaque
stringData:
  postgres-db: inventory_service_db
  postgres-user: inventory_admin
  postgres-password: inventory_pass_123
  jwt-secret: "3cfa76ef14937c1c0ea190febb3f6b8f2d1b1c7e4a5d8f9a0b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4"