spring.application.name=inventory-service

# JWT Configuration
jwt.secret=3cfa76ef14937c1c0ea190febb3f6b8f2d1b1c7e4a5d8f9a0b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4
jwt.expiration=86400000

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/inventory_service_db
spring.datasource.username=inventory_admin
spring.datasource.password=inventory_pass_123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.inventory_service.event
spring.kafka.consumer.group-id=inventory-service-group
